# Generated by Django 5.0 on 2023-12-20 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='construction',
            name='Location',
            field=models.CharField(choices=[('Paxtakor', 'Paxtakor'), ('Olmazor', 'Olmazor')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='construction',
            name='image',
            field=models.ImageField(upload_to='constructions/'),
        ),
        migrations.CreateModel(
            name='ConstructionThreeDImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='construction_three_d_images/')),
                ('construction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='constructions.construction')),
                ('neighbours', models.ManyToManyField(blank=True, to='constructions.constructionthreedimage')),
            ],
        ),
    ]
