# Generated by Django 5.0 on 2023-12-21 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructions', '0002_construction_location_alter_construction_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubwayStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('addressformatted', models.CharField(max_length=500)),
            ],
        ),
        migrations.RemoveField(
            model_name='construction',
            name='Location',
        ),
        migrations.AlterField(
            model_name='construction',
            name='image',
            field=models.ImageField(upload_to='constructions/images/'),
        ),
        migrations.AddField(
            model_name='construction',
            name='subway_station_location',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='constructions.subwaystation'),
        ),
    ]
