# Generated by Django 5.0 on 2023-12-21 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructions', '0003_subwaystation_remove_construction_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
