# Generated by Django 5.0 on 2023-12-21 05:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('constructions', '0005_remove_order_name_constructionthreedimage_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='constructionthreedimage',
            name='construction',
        ),
        migrations.AddField(
            model_name='construction',
            name='threedimage',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='constructions.constructionthreedimage'),
        ),
    ]
