# Generated by Django 5.0 on 2023-12-21 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_contents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('person', models.CharField(max_length=100)),
                ('person_image', models.ImageField(upload_to='uploads/web_contents/person_images/')),
                ('on_what_platform', models.CharField(blank=True, choices=[('Telegram', 'Telegram'), ('Facebook', 'Facebook'), ('Instagram', 'Instagram')], default='Telegram', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
