# Generated by Django 5.0 on 2023-12-24 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_contents", "0002_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailToBeContacted",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("contacted_yet", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
